version: '3'

services:
  crawling-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: crawling-server-1
    ports:
      - "5001:5001"

  crawling-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    image: crawling-server-2
    ports:
      - "5002:5001"